services:
  - type: web
    name: ai-image-generator
    env: node
    buildCommand: ""
    startCommand: node api-server.js
    envVars:
      - key: FAL_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    scaling:
      minInstances: 1
      maxInstances: 3